create table Businesses
(
business_id varchar(22) not null primary key,
name varchar(70) not null,
address varchar(130) not null,
city varchar(100) not null,
state varchar(5) not null,
postal_code varchar(10) not null,
latitude float not null,
longitude float not null,
stars float not null,
review_count int null,
is_open int null,
categories varchar(1500) null
);

create table Business_Attributes
(
business_id varchar(22) not null foreign key references Businesses(business_id) ,							
AcceptsInsurance bit null,
AgesAllowed bit null,
Alcohol bit null,
Ambience bit null,
Ambience_casual bit null,
Ambience_classy bit null,
Ambience_divey bit null,
Ambience_hipster bit null,
Ambience_intimate bit null,
Ambience_romantic bit null,
Ambience_touristy bit null,
Ambience_trendy bit null,
Ambience_upscale bit null,
BYOB bit null,
BYOBCorkage bit null,
BestNights bit null,
BestNights_friday bit null,
BestNights_monday bit null,
BestNights_saturday bit null,
BestNights_sunday bit null,
BestNights_thursday bit null,
BestNights_tuesday bit null,
BestNights_wednesday bit null,
BikeParking bit null,
BusinessAcceptsBitcoin bit null,
BusinessAcceptsCreditCards bit null,
BusinessParking bit null,
BusinessParking_garage bit null,
BusinessParking_lot bit null,
BusinessParking_street bit null,
BusinessParking_valet bit null,
BusinessParking_validated bit null,
ByAppointmentOnly bit null,
Caters bit null,
CoatCheck bit null,
Corkage bit null,
DietaryRestrictions bit null,
DietaryRestrictions_dairy_free bit null,
DietaryRestrictions_gluten_free bit null,
DietaryRestrictions_halal bit null,
DietaryRestrictions_kosher bit null,
DietaryRestrictions_soy_free bit null,
DietaryRestrictions_vegan bit null,
DietaryRestrictions_vegetarian bit null,
DogsAllowed bit null,
DriveThru bit null,
GoodForDancing bit null,
GoodForKids bit null,
GoodForMeal bit null,
GoodForMeal_breakfast bit null,
GoodForMeal_brunch bit null,
GoodForMeal_dessert bit null,
GoodForMeal_dinner bit null,
GoodForMeal_latenight bit null,
GoodForMeal_lunch bit null,
HairSpecializesIn bit null,
HairSpecializesIn_africanamerican bit null,
HairSpecializesIn_asian bit null,
HairSpecializesIn_coloring bit null,
HairSpecializesIn_curly bit null,
HairSpecializesIn_extensions bit null,
HairSpecializesIn_kids bit null,
HairSpecializesIn_perms bit null,
HairSpecializesIn_straightperms bit null,
HappyHour bit null,
HasTV bit null,
Music bit null,
Music_background_music bit null,
Music_dj bit null,
Music_jukebox bit null,
Music_karaoke bit null,
Music_live bit null,
Music_no_music bit null,
Music_video bit null,
NoiseLevel bit null,
Open24Hours bit null,
OutdoorSeating bit null,
RestaurantsAttire bit null,
RestaurantsCounterService bit null,
RestaurantsDelivery bit null,
RestaurantsGoodForGroups bit null,
RestaurantsPriceRange2 bit null,
RestaurantsReservations bit null,
RestaurantsTableService bit null,
RestaurantsTakeOut bit null,
Smoking bit null,
WheelchairAccessible bit null,
WiFi bit null,
primary key(business_id)
)

